#!/bin/sh

# default handlers for hyprevents
#
# override the function in your own events
# file to provide a custom handler
#
# comments inside each handler list the variables
# that are set when the handler is invoked

HYPRPROP_PID='/tmp/hyprprop.pid'

event_workspace() {
  : # WORKSPACENAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_focusedmon() {
  : # MONNAME WORKSPACENAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_activewindow() {
  : # WINDOWCLASS WINDOWTITLE
}

event_fullscreen() {
  : # ENTER (0 if leaving fullscreen, 1 if entering)
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_monitorremoved() {
  : # MONITORNAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_monitoradded() {
  : # MONITORNAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_createworkspace() {
  : # WORKSPACENAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_destroyworkspace() {
  : # WORKSPACENAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_moveworkspace() {
  : # WORKSPACENAME MONNAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_activelayout() {
  : # KEYBOARDNAME LAYOUTNAME
}

event_openwindow() {
  : # WINDOWADDRESS WORKSPACENAME WINDOWCLASS WINDOWTITLE
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_closewindow() {
  : # WINDOWADDRESS
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_movewindow() {
  : # WINDOWADDRESS WORKSPACENAME
  kill -USR1 "$(cat "$HYPRPROP_PID")"
}

event_openlayer() {
  : # NAMESPACE
}

event_closelayer() {
  : # NAMESPACE
}

event_submap() {
  : # SUBMAPNAME
}
